"""Observability utilities (metrics, logging, tracing)."""

from .logging import configure_logging
from .metrics import (
    INGEST_ARTIFACTS_TOTAL,
    INGEST_CHUNKS_TOTAL,
    INGEST_DURATION_SECONDS,
    INGEST_LAST_RUN_STATUS,
    INGEST_LAST_RUN_TIMESTAMP,
    COVERAGE_LAST_RUN_STATUS,
    COVERAGE_LAST_RUN_TIMESTAMP,
    COVERAGE_MISSING_ARTIFACTS,
    SEARCH_REQUESTS_TOTAL,
    SEARCH_GRAPH_CACHE_EVENTS,
    SEARCH_GRAPH_LOOKUP_SECONDS,
    SEARCH_SCORE_DELTA,
    GRAPH_MIGRATION_LAST_STATUS,
    GRAPH_MIGRATION_LAST_TIMESTAMP,
)
from .tracing import configure_tracing

__all__ = [
    "configure_logging",
    "configure_tracing",
    "INGEST_ARTIFACTS_TOTAL",
    "INGEST_CHUNKS_TOTAL",
    "INGEST_DURATION_SECONDS",
    "INGEST_LAST_RUN_STATUS",
    "INGEST_LAST_RUN_TIMESTAMP",
    "COVERAGE_LAST_RUN_STATUS",
    "COVERAGE_LAST_RUN_TIMESTAMP",
    "COVERAGE_MISSING_ARTIFACTS",
    "SEARCH_REQUESTS_TOTAL",
    "SEARCH_GRAPH_CACHE_EVENTS",
    "SEARCH_GRAPH_LOOKUP_SECONDS",
    "SEARCH_SCORE_DELTA",
    "GRAPH_MIGRATION_LAST_STATUS",
    "GRAPH_MIGRATION_LAST_TIMESTAMP",
]
