x-env-file: &gateway-env
  env_file:
    - ./gateway.env

services:
  gateway:
    image: ${KM_IMAGE:-duskmantle/km:test}
    <<: *gateway-env
    environment:
      KM_QDRANT_URL: "http://qdrant:6333"
      KM_NEO4J_URI: "bolt://neo4j:7687"
      KM_AUTH_ENABLED: "true"
    depends_on:
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./config/gateway:/opt/knowledge/var
      - ./repo:/workspace/repo
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=1000,gid=1000,mode=1777

  neo4j:
    image: ${KM_NEO4J_IMAGE:-neo4j:5.26.0}
    environment:
      NEO4J_AUTH: "neo4j/${KM_NEO4J_PASSWORD:-neo4jadmin}"
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 2G
    volumes:
      - ./config/neo4j/data:/data
      - ./config/neo4j/logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${KM_NEO4J_PASSWORD:-neo4jadmin} 'SHOW DATABASES'"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

  qdrant:
    image: ${KM_QDRANT_IMAGE:-qdrant/qdrant:v1.15.5}
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - ./config/qdrant:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          bash -c 'exec 3<>/dev/tcp/127.0.0.1/6333 &&
          printf "GET /healthz HTTP/1.0\r\n\r\n" >&3 &&
          head -n 1 <&3 | grep -q "200"'
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

networks:
  default:
    name: duskmantle-internal

# Usage:
#   mkdir -p compose/config/gateway compose/config/neo4j compose/config/qdrant compose/repo
#   cp infra/examples/docker-compose.sample.yml compose/docker-compose.yml
#   cp infra/examples/gateway.env.sample compose/gateway.env (fill tokens/passwords)
#   docker compose -f compose/docker-compose.yml up -d
#
# Only the API port (8000) is exposed by default. Uncomment port mappings under
# qdrant/neo4j if local tooling needs direct access.
