name: Neo4j Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

jobs:
  neo4j-tests:
    runs-on: ubuntu-latest
    env:
      NEO4J_TEST_URI: bolt://localhost:7687
      NEO4J_TEST_USER: neo4j
      NEO4J_TEST_PASSWORD: temp-password
    services:
      neo4j:
        image: neo4j:5
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/temp-password
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]

      - name: Wait for Neo4j
        env:
          NEO4J_HOME: /var/lib/neo4j
        run: |
          set -euo pipefail
          . .venv/bin/activate
          python - <<'PY'
          import os
          import time
          from neo4j import GraphDatabase, exceptions

          uri = os.environ["NEO4J_TEST_URI"]
          user = os.environ.get("NEO4J_TEST_USER", "neo4j")
          password = os.environ.get("NEO4J_TEST_PASSWORD", "neo4jadmin")
          deadline = time.time() + 180
          last_error = None

          while time.time() < deadline:
              try:
                  with GraphDatabase.driver(uri, auth=(user, password)) as driver:
                      driver.verify_connectivity()
                  print("Neo4j is ready.")
                  break
              except exceptions.Neo4jError as exc:
                  last_error = exc
              except Exception as exc:  # noqa: BLE001 - log generic failures for diagnostics
                  last_error = exc
              time.sleep(5)
          else:
              raise SystemExit(f"Neo4j did not become ready in time: {last_error}")
          PY

      - name: Run Neo4j integration tests
        run: |
          . .venv/bin/activate
          pytest -m neo4j -ra
          pytest -m mcp_smoke --maxfail=1 --disable-warnings
