name: Neo4j Integration Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

jobs:
  neo4j-tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: duskmantle/km:${{ github.sha }}
      KM_ADMIN_TOKEN: maintainer-token
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]

      - name: Install Node dependencies
        run: npm ci

      - name: Install Playwright browsers (CI only)
        run: npx playwright install chromium

      - name: Build container image
        run: docker build --network=host -t "$IMAGE_TAG" .

      - name: Launch gateway container
        run: |
          docker run -d --name km-integration \
            --network host \
            -e KM_ADMIN_TOKEN="$KM_ADMIN_TOKEN" \
            "$IMAGE_TAG"

      - name: Wait for gateway readiness
        run: |
          set -euo pipefail
          for i in {1..60}; do
            if docker exec km-integration curl -fsS http://127.0.0.1:8000/readyz >/dev/null; then
              exit 0
            fi
            sleep 5
          done
          echo "Gateway failed to become ready" >&2
          docker logs km-integration || true
          exit 1

      - name: Install dev extras inside container
        run: |
          docker exec km-integration bash -lc '. /opt/knowledge/.venv/bin/activate && pip install -e "/opt/knowledge/app[dev]"'

      - name: Run Neo4j integration tests inside container
        run: |
          docker exec km-integration bash -lc '. /opt/knowledge/.venv/bin/activate && cd /opt/knowledge/app && NEO4J_TEST_URI=bolt://127.0.0.1:7687 pytest -m neo4j -ra'

      - name: Run MCP smoke tests
        run: |
          . .venv/bin/activate
          pytest -m mcp_smoke --maxfail=1 --disable-warnings

      - name: Run Playwright UI smoke tests
        run: |
          . .venv/bin/activate
          npx playwright test

      - name: Tear down container
        if: always()
        run: docker rm -f km-integration || true
