name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests
        run: pytest

      - name: Build wheel
        run: |
          python -m pip install build
          scripts/build-wheel.sh dist/release

      - name: Free disk space for Docker build
        run: |
          set -euxo pipefail
          df -h
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"/CodeQL || true
          docker system prune -af || true
          df -h

      - name: Build docker image
        run: scripts/build-image.sh duskmantle/km:${{ github.ref_name }}

      - name: Push image to GHCR
        env:
          OWNER: ${{ github.repository_owner }}
          TAG: ${{ github.ref_name }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          set -euo pipefail
          owner_lc=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          image="ghcr.io/${owner_lc}/duskmantle-km:${TAG}"
          token="$GHCR_TOKEN"
          if [ -z "$token" ]; then
            token="${{ secrets.GITHUB_TOKEN }}"
          fi
          echo "$token" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker tag duskmantle/km:${TAG} "$image"
          docker push "$image"

      - name: Generate checksums
        run: |
          scripts/checksums.sh dist/release dist/SHA256SUMS
          scripts/checksums.sh dist dist/IMAGE_SHA256SUMS

      - name: Smoke test container
        run: ./infra/smoke-test.sh duskmantle/km:${{ github.ref_name }}

      - name: Run MCP smoke tests
        run: pytest -m mcp_smoke --maxfail=1 --disable-warnings

      - name: Run Neo4j integration slice
        env:
          NEO4J_TEST_URI: bolt://127.0.0.1:7687
          NEO4J_TEST_PASSWORD: neo4jadmin
        run: |
          set -euo pipefail
          docker run -d --name km-gateway-ci \
            --network host \
            -e KM_GRAPH_AUTO_MIGRATE=true \
            -e KM_NEO4J_PASSWORD=${NEO4J_TEST_PASSWORD} \
            duskmantle/km:${{ github.ref_name }}
          trap 'docker rm -f km-gateway-ci >/dev/null 2>&1 || true' EXIT
          docker exec km-gateway-ci bash -lc '. /opt/knowledge/.venv/bin/activate && pip install -e "/opt/knowledge/app[dev]"'
          for i in {1..60}; do
            if docker exec km-gateway-ci curl -fsS http://127.0.0.1:8000/readyz >/dev/null; then
              ready=1
              break
            fi
            sleep 5
          done
          if [ "${ready:-0}" != "1" ]; then
            docker logs km-gateway-ci || true
            echo "Gateway failed to become ready" >&2
            exit 1
          fi
          docker exec -e NEO4J_TEST_URI="${NEO4J_TEST_URI}" km-gateway-ci bash -lc '. /opt/knowledge/.venv/bin/activate && cd /opt/knowledge/app && pytest -m neo4j -ra'

      - name: Create or update GitHub Release
        env:
          TAG: ${{ github.ref_name }}
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          tag="${TAG}"
          repo="${REPO}"
          # Ensure files exist; allow glob expansion to fail gracefully if no wheels yet
          files=(
            dist/release/*.whl
            dist/SHA256SUMS
            dist/IMAGE_SHA256SUMS
            CHANGELOG.md
            docs/dashboards/gateway_overview.json
          )
          # Filter only existing files
          upload_files=()
          for f in "${files[@]}"; do
            for match in $f; do
              if [ -f "$match" ]; then
                upload_files+=("$match")
              fi
            done
          done
          if gh release view "$tag" -R "$repo" >/dev/null 2>&1; then
            # Update existing draft or release and upload files
            gh release edit "$tag" --title "$tag" --draft --notes-file CHANGELOG.md -R "$repo"
            if [ ${#upload_files[@]} -gt 0 ]; then
              gh release upload "$tag" "${upload_files[@]}" --clobber -R "$repo"
            fi
          else
            # Create a new draft release with assets
            if [ ${#upload_files[@]} -gt 0 ]; then
              gh release create "$tag" --title "$tag" --draft --notes-file CHANGELOG.md -R "$repo" "${upload_files[@]}"
            else
              gh release create "$tag" --title "$tag" --draft --notes-file CHANGELOG.md -R "$repo"
            fi
          fi
